'use client';

import React, { useState } from 'react';
import {
  Target,
  TrendingUp,
  TrendingDown,
  AlertTriangle,
  CheckCircle,
  Info,
  BarChart3,
  PieChart,
  Activity,
  Zap,
  Shield,
  Clock,
  Users,
  Code,
  GitBranch,
  Layers,
  Database,
  Network,
  FileText,
  Download,
  Share2,
  Copy,
  Eye,
  EyeOff,
  ChevronDown,
  ChevronRight,
  ExternalLink,
  Save,
  RefreshCw
} from 'lucide-react';

interface ImpactAnalysisProps {
  refactoringPlan: {
    steps: Array<{
      id: string;
      title: string;
      impact: {
        filesAffected: number;
        methodsChanged: number;
        dependenciesModified: number;
        riskLevel: 'low' | 'medium' | 'high';
      };
    }>;
    overallImpact: {
      totalFiles: number;
      totalMethods: number;
      complexityReduction: number;
      maintainabilityImprovement: number;
      performanceImpact: 'positive' | 'neutral' | 'negative';
    };
  };
  onExport?: () => void;
  onShare?: () => void;
}

export default function ImpactAnalysis({
  refactoringPlan,
  onExport,
  onShare
}: ImpactAnalysisProps) {
  const [selectedMetric, setSelectedMetric] = useState<'complexity' | 'maintainability' | 'performance' | 'risk'>('complexity');
  const [showDetails, setShowDetails] = useState(true);
  const [copied, setCopied] = useState<string | null>(null);

  const copyToClipboard = async (text: string, type: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(type);
      setTimeout(() => setCopied(null), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const getRiskColor = (risk: string) => {
    switch (risk) {
      case 'low': return 'text-green-400 bg-green-500/20 border-green-500/50';
      case 'medium': return 'text-yellow-400 bg-yellow-500/20 border-yellow-500/50';
      case 'high': return 'text-red-400 bg-red-500/20 border-red-500/50';
      default: return 'text-gray-400 bg-gray-500/20 border-gray-500/50';
    }
  };

  const getPerformanceColor = (impact: string) => {
    switch (impact) {
      case 'positive': return 'text-green-400';
      case 'negative': return 'text-red-400';
      default: return 'text-slate-400';
    }
  };

  const getPerformanceIcon = (impact: string) => {
    switch (impact) {
      case 'positive': return <TrendingUp className="w-4 h-4 text-green-400" />;
      case 'negative': return <TrendingDown className="w-4 h-4 text-red-400" />;
      default: return <Activity className="w-4 h-4 text-slate-400" />;
    }
  };

  const generateImpactReport = () => {
    return `# Refactoring Impact Analysis Report

## Overall Impact Summary
- **Total Files Affected:** ${refactoringPlan.overallImpact.totalFiles}
- **Total Methods Changed:** ${refactoringPlan.overallImpact.totalMethods}
- **Complexity Reduction:** ${refactoringPlan.overallImpact.complexityReduction}%
- **Maintainability Improvement:** ${refactoringPlan.overallImpact.maintainabilityImprovement}%
- **Performance Impact:** ${refactoringPlan.overallImpact.performanceImpact.toUpperCase()}

## Step-by-Step Impact Analysis
${refactoringPlan.steps.map((step, index) => `
### Step ${index + 1}: ${step.title}
- **Files Affected:** ${step.impact.filesAffected}
- **Methods Changed:** ${step.impact.methodsChanged}
- **Dependencies Modified:** ${step.impact.dependenciesModified}
- **Risk Level:** ${step.impact.riskLevel.toUpperCase()}
`).join('')}

---
*Generated by ${BrandName} - AI-Powered Code Refactoring*
`;
  };

  const metrics = [
    {
      id: 'complexity',
      title: 'Complexity Reduction',
      value: `${refactoringPlan.overallImpact.complexityReduction}%`,
      icon: <BarChart3 className="w-5 h-5" />,
      color: 'text-green-400',
      bgColor: 'bg-green-500/20',
      borderColor: 'border-green-500/50'
    },
    {
      id: 'maintainability',
      title: 'Maintainability Improvement',
      value: `${refactoringPlan.overallImpact.maintainabilityImprovement}%`,
      icon: <TrendingUp className="w-5 h-5" />,
      color: 'text-blue-400',
      bgColor: 'bg-blue-500/20',
      borderColor: 'border-blue-500/50'
    },
    {
      id: 'performance',
      title: 'Performance Impact',
      value: refactoringPlan.overallImpact.performanceImpact.toUpperCase(),
      icon: getPerformanceIcon(refactoringPlan.overallImpact.performanceImpact),
      color: getPerformanceColor(refactoringPlan.overallImpact.performanceImpact),
      bgColor: refactoringPlan.overallImpact.performanceImpact === 'positive' ? 'bg-green-500/20' : 
               refactoringPlan.overallImpact.performanceImpact === 'negative' ? 'bg-red-500/20' : 'bg-slate-500/20',
      borderColor: refactoringPlan.overallImpact.performanceImpact === 'positive' ? 'border-green-500/50' : 
                  refactoringPlan.overallImpact.performanceImpact === 'negative' ? 'border-red-500/50' : 'border-slate-500/50'
    },
    {
      id: 'risk',
      title: 'Overall Risk Level',
      value: refactoringPlan.steps.some(s => s.impact.riskLevel === 'high') ? 'HIGH' : 
             refactoringPlan.steps.some(s => s.impact.riskLevel === 'medium') ? 'MEDIUM' : 'LOW',
      icon: <Shield className="w-5 h-5" />,
      color: refactoringPlan.steps.some(s => s.impact.riskLevel === 'high') ? 'text-red-400' :
             refactoringPlan.steps.some(s => s.impact.riskLevel === 'medium') ? 'text-yellow-400' : 'text-green-400',
      bgColor: refactoringPlan.steps.some(s => s.impact.riskLevel === 'high') ? 'bg-red-500/20' :
               refactoringPlan.steps.some(s => s.impact.riskLevel === 'medium') ? 'bg-yellow-500/20' : 'bg-green-500/20',
      borderColor: refactoringPlan.steps.some(s => s.impact.riskLevel === 'high') ? 'border-red-500/50' :
                   refactoringPlan.steps.some(s => s.impact.riskLevel === 'medium') ? 'border-yellow-500/50' : 'border-green-500/50'
    }
  ];

  return (
    <div className="bg-slate-800 rounded-lg border border-slate-700">
      {/* Header */}
      <div className="p-6 border-b border-slate-700">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="text-xl font-bold text-white flex items-center">
              <Target className="w-5 h-5 mr-2 text-purple-400" />
              Impact Analysis
            </h3>
            <p className="text-slate-400 mt-1">
              Comprehensive analysis of refactoring impact on code quality and system architecture
            </p>
          </div>
          <div className="flex space-x-2">
            <button
              onClick={() => setShowDetails(!showDetails)}
              className="px-3 py-1 bg-slate-700 hover:bg-slate-600 text-white rounded text-sm flex items-center"
            >
              {showDetails ? <EyeOff className="w-4 h-4 mr-1" /> : <Eye className="w-4 h-4 mr-1" />}
              {showDetails ? 'Hide' : 'Show'} Details
            </button>
            <button
              onClick={() => copyToClipboard(generateImpactReport(), 'report')}
              className="px-3 py-1 bg-slate-700 hover:bg-slate-600 text-white rounded text-sm flex items-center"
            >
              {copied === 'report' ? <CheckCircle className="w-4 h-4 mr-1 text-green-400" /> : <Copy className="w-4 h-4 mr-1" />}
              Copy Report
            </button>
          </div>
        </div>

        {/* Key Metrics */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          {metrics.map((metric) => (
            <div
              key={metric.id}
              className={`rounded-lg p-4 border ${metric.bgColor} ${metric.borderColor} cursor-pointer transition-all ${
                selectedMetric === metric.id ? 'ring-2 ring-blue-500' : 'hover:scale-105'
              }`}
              onClick={() => setSelectedMetric(metric.id as any)}
            >
              <div className="flex items-center justify-between mb-2">
                <div className={`${metric.color}`}>{metric.icon}</div>
                <div className={`text-2xl font-bold ${metric.color}`}>{metric.value}</div>
              </div>
              <div className="text-sm text-slate-400">{metric.title}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Detailed Analysis */}
      {showDetails && (
        <div className="p-6">
          {/* Overall Impact Summary */}
          <div className="mb-6">
            <h4 className="text-lg font-semibold text-white mb-4 flex items-center">
              <BarChart3 className="w-5 h-5 mr-2 text-blue-400" />
              Overall Impact Summary
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              <div className="bg-slate-700 rounded-lg p-4">
                <div className="text-2xl font-bold text-blue-400">{refactoringPlan.overallImpact.totalFiles}</div>
                <div className="text-sm text-slate-400">Files Affected</div>
              </div>
              <div className="bg-slate-700 rounded-lg p-4">
                <div className="text-2xl font-bold text-green-400">{refactoringPlan.overallImpact.totalMethods}</div>
                <div className="text-sm text-slate-400">Methods Changed</div>
              </div>
              <div className="bg-slate-700 rounded-lg p-4">
                <div className="text-2xl font-bold text-purple-400">{refactoringPlan.overallImpact.complexityReduction}%</div>
                <div className="text-sm text-slate-400">Complexity Reduction</div>
              </div>
              <div className="bg-slate-700 rounded-lg p-4">
                <div className="text-2xl font-bold text-yellow-400">{refactoringPlan.overallImpact.maintainabilityImprovement}%</div>
                <div className="text-sm text-slate-400">Maintainability Improvement</div>
              </div>
            </div>
          </div>

          {/* Step-by-Step Impact */}
          <div className="mb-6">
            <h4 className="text-lg font-semibold text-white mb-4 flex items-center">
              <Layers className="w-5 h-5 mr-2 text-green-400" />
              Step-by-Step Impact Analysis
            </h4>
            <div className="space-y-4">
              {refactoringPlan.steps.map((step, index) => (
                <div key={step.id} className="bg-slate-700 rounded-lg p-4 border border-slate-600">
                  <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center space-x-3">
                      <div className="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center text-white font-bold text-sm">
                        {index + 1}
                      </div>
                      <div>
                        <h5 className="text-white font-semibold">{step.title}</h5>
                        <div className="text-sm text-slate-400">Step {index + 1} of {refactoringPlan.steps.length}</div>
                      </div>
                    </div>
                    <span className={`px-3 py-1 rounded-full text-sm font-medium border ${getRiskColor(step.impact.riskLevel)}`}>
                      {step.impact.riskLevel.toUpperCase()} RISK
                    </span>
                  </div>
                  
                  <div className="grid grid-cols-3 gap-4">
                    <div className="bg-slate-800 rounded-lg p-3">
                      <div className="text-lg font-bold text-blue-400">{step.impact.filesAffected}</div>
                      <div className="text-sm text-slate-400">Files Affected</div>
                    </div>
                    <div className="bg-slate-800 rounded-lg p-3">
                      <div className="text-lg font-bold text-green-400">{step.impact.methodsChanged}</div>
                      <div className="text-sm text-slate-400">Methods Changed</div>
                    </div>
                    <div className="bg-slate-800 rounded-lg p-3">
                      <div className="text-lg font-bold text-purple-400">{step.impact.dependenciesModified}</div>
                      <div className="text-sm text-slate-400">Dependencies Modified</div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Risk Assessment */}
          <div className="mb-6">
            <h4 className="text-lg font-semibold text-white mb-4 flex items-center">
              <Shield className="w-5 h-5 mr-2 text-yellow-400" />
              Risk Assessment
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="bg-slate-700 rounded-lg p-4">
                <div className="flex items-center justify-between mb-2">
                  <div className="text-green-400">Low Risk Steps</div>
                  <div className="text-2xl font-bold text-green-400">
                    {refactoringPlan.steps.filter(s => s.impact.riskLevel === 'low').length}
                  </div>
                </div>
                <div className="text-sm text-slate-400">Safe to execute</div>
              </div>
              <div className="bg-slate-700 rounded-lg p-4">
                <div className="flex items-center justify-between mb-2">
                  <div className="text-yellow-400">Medium Risk Steps</div>
                  <div className="text-2xl font-bold text-yellow-400">
                    {refactoringPlan.steps.filter(s => s.impact.riskLevel === 'medium').length}
                  </div>
                </div>
                <div className="text-sm text-slate-400">Requires careful review</div>
              </div>
              <div className="bg-slate-700 rounded-lg p-4">
                <div className="flex items-center justify-between mb-2">
                  <div className="text-red-400">High Risk Steps</div>
                  <div className="text-2xl font-bold text-red-400">
                    {refactoringPlan.steps.filter(s => s.impact.riskLevel === 'high').length}
                  </div>
                </div>
                <div className="text-sm text-slate-400">Requires extensive testing</div>
              </div>
            </div>
          </div>

          {/* Performance Impact */}
          <div>
            <h4 className="text-lg font-semibold text-white mb-4 flex items-center">
              <Activity className="w-5 h-5 mr-2 text-purple-400" />
              Performance Impact Analysis
            </h4>
            <div className="bg-slate-700 rounded-lg p-4">
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-white font-semibold">Overall Performance Impact</div>
                  <div className="text-slate-400">Expected performance change after refactoring</div>
                </div>
                <div className="flex items-center space-x-2">
                  {getPerformanceIcon(refactoringPlan.overallImpact.performanceImpact)}
                  <span className={`text-lg font-bold ${getPerformanceColor(refactoringPlan.overallImpact.performanceImpact)}`}>
                    {refactoringPlan.overallImpact.performanceImpact.toUpperCase()}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Action Buttons */}
      <div className="p-6 border-t border-slate-700 bg-slate-900/50">
        <div className="flex items-center justify-between">
          <div className="text-sm text-slate-400">
            Impact analysis generated by {BrandName}
          </div>
          <div className="flex space-x-3">
            <button
              onClick={() => copyToClipboard(generateImpactReport(), 'full')}
              className="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition-colors flex items-center"
            >
              <Copy className="w-4 h-4 mr-2" />
              Copy Full Report
            </button>
            <button
              onClick={onExport}
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors flex items-center"
            >
              <Download className="w-4 h-4 mr-2" />
              Export Report
            </button>
            <button
              onClick={onShare}
              className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg transition-colors flex items-center"
            >
              <Share2 className="w-4 h-4 mr-2" />
              Share Analysis
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
