'use client';

import React, { useState } from 'react';
import { BrandName } from './BrandLogo';
import {
  FileText,
  BookOpen,
  Target,
  CheckCircle,
  AlertTriangle,
  Info,
  Lightbulb,
  TestTube,
  GitBranch,
  Code,
  Layers,
  Zap,
  Shield,
  TrendingUp,
  Download,
  Share2,
  Copy,
  Eye,
  EyeOff,
  ChevronDown,
  ChevronRight,
  ExternalLink,
  Save,
  RefreshCw
} from 'lucide-react';

interface RefactoringDocumentationProps {
  refactoringStep: {
    id: string;
    title: string;
    description: string;
    type: string;
    documentation: {
      rationale: string;
      benefits: string[];
      risks: string[];
      alternatives: string[];
      testingStrategy: string;
    };
    impact: {
      filesAffected: number;
      methodsChanged: number;
      dependenciesModified: number;
      riskLevel: 'low' | 'medium' | 'high';
    };
  };
  onExport?: () => void;
  onShare?: () => void;
}

export default function RefactoringDocumentation({
  refactoringStep,
  onExport,
  onShare
}: RefactoringDocumentationProps) {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set(['rationale', 'benefits']));
  const [copied, setCopied] = useState<string | null>(null);

  const toggleSection = (section: string) => {
    const newExpanded = new Set(expandedSections);
    if (newExpanded.has(section)) {
      newExpanded.delete(section);
    } else {
      newExpanded.add(section);
    }
    setExpandedSections(newExpanded);
  };

  const copyToClipboard = async (text: string, type: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(type);
      setTimeout(() => setCopied(null), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const getRiskColor = (risk: string) => {
    switch (risk) {
      case 'low': return 'text-green-400 bg-green-500/20 border-green-500/50';
      case 'medium': return 'text-yellow-400 bg-yellow-500/20 border-yellow-500/50';
      case 'high': return 'text-red-400 bg-red-500/20 border-red-500/50';
      default: return 'text-gray-400 bg-gray-500/20 border-gray-500/50';
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'extract': return <Code className="w-5 h-5" />;
      case 'move': return <GitBranch className="w-5 h-5" />;
      case 'rename': return <Target className="w-5 h-5" />;
      case 'split': return <Layers className="w-5 h-5" />;
      case 'merge': return <Zap className="w-5 h-5" />;
      case 'optimize': return <TrendingUp className="w-5 h-5" />;
      default: return <Code className="w-5 h-5" />;
    }
  };

  const generateDocumentation = () => {
    return `# Refactoring Documentation

## ${refactoringStep.title}

**Type:** ${refactoringStep.type}  
**Risk Level:** ${refactoringStep.impact.riskLevel.toUpperCase()}  
**Files Affected:** ${refactoringStep.impact.filesAffected}  
**Methods Changed:** ${refactoringStep.impact.methodsChanged}  
**Dependencies Modified:** ${refactoringStep.impact.dependenciesModified}

### Description
${refactoringStep.description}

### Rationale
${refactoringStep.documentation.rationale}

### Benefits
${refactoringStep.documentation.benefits.map(benefit => `- ${benefit}`).join('\n')}

### Risks
${refactoringStep.documentation.risks.map(risk => `- ${risk}`).join('\n')}

### Alternatives
${refactoringStep.documentation.alternatives.map(alt => `- ${alt}`).join('\n')}

### Testing Strategy
${refactoringStep.documentation.testingStrategy}

---
            *Generated by {BrandName} - AI-Powered Code Refactoring*
`;
  };

  const sections = [
    {
      id: 'overview',
      title: 'Overview',
      icon: <Info className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-slate-700 rounded-lg p-4">
              <div className="text-sm text-slate-400">Type</div>
              <div className="text-white font-semibold capitalize">{refactoringStep.type}</div>
            </div>
            <div className="bg-slate-700 rounded-lg p-4">
              <div className="text-sm text-slate-400">Risk Level</div>
              <div className={`font-semibold ${getRiskColor(refactoringStep.impact.riskLevel).split(' ')[0]}`}>
                {refactoringStep.impact.riskLevel.toUpperCase()}
              </div>
            </div>
          </div>
          <div className="grid grid-cols-3 gap-4">
            <div className="bg-slate-700 rounded-lg p-4">
              <div className="text-2xl font-bold text-blue-400">{refactoringStep.impact.filesAffected}</div>
              <div className="text-sm text-slate-400">Files Affected</div>
            </div>
            <div className="bg-slate-700 rounded-lg p-4">
              <div className="text-2xl font-bold text-green-400">{refactoringStep.impact.methodsChanged}</div>
              <div className="text-sm text-slate-400">Methods Changed</div>
            </div>
            <div className="bg-slate-700 rounded-lg p-4">
              <div className="text-2xl font-bold text-purple-400">{refactoringStep.impact.dependenciesModified}</div>
              <div className="text-sm text-slate-400">Dependencies</div>
            </div>
          </div>
        </div>
      )
    },
    {
      id: 'rationale',
      title: 'Rationale',
      icon: <Lightbulb className="w-5 h-5" />,
      content: (
        <div className="bg-slate-700 rounded-lg p-4">
          <p className="text-slate-300 leading-relaxed">{refactoringStep.documentation.rationale}</p>
        </div>
      )
    },
    {
      id: 'benefits',
      title: 'Benefits',
      icon: <CheckCircle className="w-5 h-5" />,
      content: (
        <div className="space-y-3">
          {refactoringStep.documentation.benefits.map((benefit, index) => (
            <div key={index} className="flex items-start space-x-3 bg-slate-700 rounded-lg p-4">
              <CheckCircle className="w-5 h-5 text-green-400 mt-0.5 flex-shrink-0" />
              <p className="text-slate-300">{benefit}</p>
            </div>
          ))}
        </div>
      )
    },
    {
      id: 'risks',
      title: 'Risks & Considerations',
      icon: <AlertTriangle className="w-5 h-5" />,
      content: (
        <div className="space-y-3">
          {refactoringStep.documentation.risks.map((risk, index) => (
            <div key={index} className="flex items-start space-x-3 bg-slate-700 rounded-lg p-4">
              <AlertTriangle className="w-5 h-5 text-yellow-400 mt-0.5 flex-shrink-0" />
              <p className="text-slate-300">{risk}</p>
            </div>
          ))}
        </div>
      )
    },
    {
      id: 'alternatives',
      title: 'Alternative Approaches',
      icon: <GitBranch className="w-5 h-5" />,
      content: (
        <div className="space-y-3">
          {refactoringStep.documentation.alternatives.map((alternative, index) => (
            <div key={index} className="flex items-start space-x-3 bg-slate-700 rounded-lg p-4">
              <Info className="w-5 h-5 text-blue-400 mt-0.5 flex-shrink-0" />
              <p className="text-slate-300">{alternative}</p>
            </div>
          ))}
        </div>
      )
    },
    {
      id: 'testing',
      title: 'Testing Strategy',
      icon: <TestTube className="w-5 h-5" />,
      content: (
        <div className="bg-slate-700 rounded-lg p-4">
          <p className="text-slate-300 leading-relaxed">{refactoringStep.documentation.testingStrategy}</p>
        </div>
      )
    }
  ];

  return (
    <div className="bg-slate-800 rounded-lg border border-slate-700">
      {/* Header */}
      <div className="p-6 border-b border-slate-700">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center space-x-3">
            {getTypeIcon(refactoringStep.type)}
            <div>
              <h3 className="text-xl font-bold text-white">{refactoringStep.title}</h3>
              <p className="text-slate-400">{refactoringStep.description}</p>
            </div>
          </div>
          <div className="flex space-x-2">
            <button
              onClick={() => copyToClipboard(generateDocumentation(), 'doc')}
              className="px-3 py-1 bg-slate-700 hover:bg-slate-600 text-white rounded text-sm flex items-center"
            >
              {copied === 'doc' ? <CheckCircle className="w-4 h-4 mr-1 text-green-400" /> : <Copy className="w-4 h-4 mr-1" />}
              Copy Doc
            </button>
            <button
              onClick={onExport}
              className="px-3 py-1 bg-blue-600 hover:bg-blue-700 text-white rounded text-sm flex items-center"
            >
              <Download className="w-4 h-4 mr-1" />
              Export
            </button>
            <button
              onClick={onShare}
              className="px-3 py-1 bg-green-600 hover:bg-green-700 text-white rounded text-sm flex items-center"
            >
              <Share2 className="w-4 h-4 mr-1" />
              Share
            </button>
          </div>
        </div>

        {/* Risk Level Badge */}
        <div className="flex items-center space-x-4">
          <span className={`px-3 py-1 rounded-full text-sm font-medium border ${getRiskColor(refactoringStep.impact.riskLevel)}`}>
            {refactoringStep.impact.riskLevel.toUpperCase()} RISK
          </span>
          <div className="text-sm text-slate-400">
            Impact: {refactoringStep.impact.filesAffected} files, {refactoringStep.impact.methodsChanged} methods
          </div>
        </div>
      </div>

      {/* Documentation Sections */}
      <div className="p-6">
        <div className="space-y-4">
          {sections.map((section) => (
            <div key={section.id} className="border border-slate-600 rounded-lg">
              <button
                onClick={() => toggleSection(section.id)}
                className="w-full flex items-center justify-between p-4 text-left hover:bg-slate-700 transition-colors"
              >
                <div className="flex items-center space-x-3">
                  <div className="text-blue-400">{section.icon}</div>
                  <h4 className="text-white font-semibold">{section.title}</h4>
                </div>
                {expandedSections.has(section.id) ? (
                  <ChevronDown className="w-5 h-5 text-slate-400" />
                ) : (
                  <ChevronRight className="w-5 h-5 text-slate-400" />
                )}
              </button>
              
              {expandedSections.has(section.id) && (
                <div className="px-4 pb-4">
                  {section.content}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Action Buttons */}
      <div className="p-6 border-t border-slate-700 bg-slate-900/50">
        <div className="flex items-center justify-between">
          <div className="text-sm text-slate-400">
            Generated by {BrandName} - AI-Powered Code Refactoring
          </div>
          <div className="flex space-x-3">
            <button
              onClick={() => copyToClipboard(generateDocumentation(), 'full')}
              className="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition-colors flex items-center"
            >
              <Copy className="w-4 h-4 mr-2" />
              Copy Full Documentation
            </button>
            <button
              onClick={onExport}
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors flex items-center"
            >
              <Download className="w-4 h-4 mr-2" />
              Export as Markdown
            </button>
            <button
              onClick={onShare}
              className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg transition-colors flex items-center"
            >
              <Share2 className="w-4 h-4 mr-2" />
              Share Documentation
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
